### ISSUE TITLE
Sign up button does work on mobile screen size

### ISSUE THREAD

**Issue by oxue** [stolinski/bboy-tools#2]
tapping sign up does nothing, but tapping the pancake button on the top right brings up the sign up interface.

**Comment by stolinski** [comment]
I'm using the meteor accounts ui package which is a pain in the ass to override all the styles, but it's why it's not showing up. I'll tweak it to open the drawer when pushed in addition to the session var.

Facebook login isn't configured either. I'll nuke out the fb login button.

**Comment by oxue** [comment]
Isn't it because the entire div for that signup screen is a child of the nav button on the top right, and when that gets swapped for the pancakes favicon the entire div goes too.

**Comment by stolinski** [comment]
Yeah, the drawer is offscreen. The signup button triggers the modal but not the drawer.

**Comment by oxue** [comment]
True; seeing that bboys are always on the go, mobile support is probably pretty important :D

**Comment by stolinski** [comment]
For real, I'll hook it up now.

**Comment by stolinski** [comment]
Fix going up now. Basically moved the nav toggle into a session variable instead of just component state to trigger it more flexibly.
